### ISSUE TITLE
Synchronisation does not work on large data dump

### ISSUE THREAD

**Issue by fguitton** [dsi-icl/optimise#679]
There is an issue when data it uploaded but is too large and the dump cannot be processed by the server.

```
PayloadTooLargeError: request entity too large
    at readStream (/root/optimise-sync/build/server.js:13024:17)
    at getRawBody (/root/optimise-sync/build/server.js:12977:12)
    at read (/root/optimise-sync/build/server.js:1025:3)
    at jsonParser (/root/optimise-sync/build/server.js:1276:5)
    at Layer.handle [as handle_request] (/root/optimise-sync/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/optimise-sync/node_modules/express/lib/router/index.js:317:13)
    at /root/optimise-sync/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/optimise-sync/node_modules/express/lib/router/index.js:335:12)
    at next (/root/optimise-sync/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/root/optimise-sync/build/server.js:1729:7)
```

**Comment by fguitton** [comment]
This should be closed when we confirm the problem doesn't reappear over time.
